---

- name: Identify the firewall used
  include_role:
    name: firewall
    tasks_from: identify.yml

- block:

    - name: Enable AH (firewalld)
      firewalld:
        rich_rule: rule protocol value="ah" accept
        permanent: yes
        state: enabled
      notify: Restart firewalld

    - name: Enable VRRP (firewalld)
      firewalld:
        rich_rule: rule protocol value="vrrp" accept
        permanent: yes
        state: enabled
      notify: Restart firewalld

  when: firewall_type == 'firewalld'

- block:

    - name: Enable AH (iptables)
      iptables:
        chain: INPUT
        protocol: ah
        jump: ACCEPT

    - name: Enable VRRP (iptables)
      iptables:
        chain: INPUT
        protocol: vrrp
        jump: ACCEPT

  when: firewall_type == 'iptables'


- block:

    - name: Enable VRRP & AH (ufw)
      ufw:
        rule: allow
        dest: "{{ keepalived_broadcast }}"
        comment: 'VRRP Broadcast'

  when: firewall_type == 'ufw'
