---

- name: Identify the firewall used
  ansible.builtin.include_role:
    name: deitkrachten.firewall
    tasks_from: identify.yml

- name: Section firewalld
  when: firewall_type == 'firewalld'
  block:

    - name: Enable AH (firewalld)
      ansible.posix.firewalld:
        rich_rule: rule protocol value="ah" accept
        permanent: yes
        state: enabled
      notify: Restart firewalld

    - name: Enable VRRP (firewalld)
      ansible.posix.firewalld:
        rich_rule: rule protocol value="vrrp" accept
        permanent: yes
        state: enabled
      notify: Restart firewalld

- name: Section iptables
  when: firewall_type == 'iptables'
  block:

    - name: Enable AH (iptables)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: ah
        jump: ACCEPT

    - name: Enable VRRP (iptables)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: vrrp
        jump: ACCEPT

- name: Section ufw
  when: firewall_type == 'ufw'
  block:

    - name: Enable VRRP & AH (ufw)
      community.general.ufw:
        rule: allow
        dest: "{{ keepalived_broadcast }}"
        comment: 'VRRP Broadcast'
