---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Enable service at boot
  ansible.builtin.service:
    name: keepalived
    enabled: yes

- name: Create keepalived_script user
  ansible.builtin.user:
    name: "{{ keepalived_script_user }}"
    comment: "User to execute keepalived check scripts"
    shell: /sbin/nologin
    expires: -1
    create_home: no

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  loop:
    - /etc/keepalived
    - /etc/keepalived/conf.d

- name: Create default keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0640"
    owner: root
    group: root
  notify: Restart keepalived

# - name: Create custom keepalived configuration
#   template:
#     src: templates/keepalived_custom.conf.j2
#     dest: /etc/keepalived/conf.d/{{ item.name }}.conf
#     owner: root
#     group: root
#     mode: "0640"
#   loop: "{{ keepalived_vrrp_instances }}"
#   loop_control:
#     label:
#       - "{{ item.name }}"
#   notify: Restart keepalived

- name: Allow binding on non-local addresses
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_set: yes
    state: present

- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml
