---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:

  - name: keepalived-master-centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - keepalived_master
  - name: keepalived-backup-centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - keepalived_backup

provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      keepalived-rockylinux8:
        ansible_python_interpreter: /usr/libexec/platform-python
scenario:
  name: default
verifier:
  name: ansible
